const about = {
  it: {
    opening: "Tra la Sicilia e le sue isole, pochi chilometri possono diventare ore.",
    introduction: "Il mare le rende vicine allo sguardo. Raggiungerle, però, può raccontare una storia molto diversa.",
    distanceTitle: ["Vicino sulla mappa.", "Lontano nel tempo."],
    distance: ["Le Eolie emergono davanti alla costa siciliana quasi come una continuazione della terra. Pantelleria appartiene allo stesso orizzonte mediterraneo, eppure raggiungere queste isole può richiedere più tempo di quanto la mappa lasci immaginare.", "La distanza si misura anche nelle attese, negli orari e nei passaggi necessari per arrivare."],
    seaTitle: "Il mare cambia le distanze.",
    sea: ["Un’isola può essere vicina e, nello stesso momento, difficile da raggiungere. Quando una partenza dipende da più passaggi, anche un breve tratto può occupare una parte importante della giornata. Da questo contrasto nasce una domanda semplice."],
    question: "Perché ciò che è così vicino deve sembrare così lontano?",
    ideaTitle: "Immaginare un modo diverso di arrivare.",
    idea: ["CAURIS Aviation nasce da questa domanda e dall’idea che tra la Sicilia e le sue isole possa esistere una mobilità più diretta."],
    continuity: ["Meno passaggi e meno distanza percepita, per dare più continuità al viaggio tra luoghi che appartengono allo stesso mare."],
    thought: ["Non cambiare la geografia.", "Cambiare il modo di attraversarla."],
    islandsTitle: "Da una sponda all’altra.",
    islands: ["Due isole diverse. Due identità diverse. Lo stesso mare.", "Il punto di partenza di CAURIS è rendere il viaggio che le collega alla Sicilia più semplice, più diretto e più naturale."],
    closingTitle: ["La geografia non cambia.", "Il modo di attraversarla sì."],
    closing: "CAURIS Aviation nasce per accorciare la distanza tra un luogo e la possibilità di raggiungerlo.",
    last: ["Sicilia e isole.", "Più vicine, finalmente, anche nel viaggio."],
    alts: ["Elicottero in volo nella luce del tramonto, sopra l’acqua", "Mare e orizzonte visti dal finestrino di un elicottero", "Rotore di un elicottero contro il cielo", "Vista della costa e del mare attraverso il cockpit"],
  },
  en: {
    opening: "Between Sicily and its islands, a few kilometres can become hours.",
    introduction: "Across the water, they look close enough to touch. Getting there can tell a very different story.",
    distanceTitle: ["Close on the map.", "Far apart in time."],
    distance: ["The Aeolian Islands rise beyond Sicily’s coast, almost an extension of the land. Pantelleria shares that Mediterranean horizon, yet reaching these islands can take longer than the map suggests.", "Distance is also measured in waiting times, timetables and the connections needed to get there."],
    seaTitle: "The sea changes distance.",
    sea: ["An island can be close by and still be difficult to reach. When a journey involves several connections, even a short distance can take up much of the day. That contrast raises a simple question."],
    question: "Why should somewhere so close feel so far away?",
    ideaTitle: "Imagining a different way to arrive.",
    idea: ["CAURIS Aviation begins with that question and the idea that a more direct way to travel between Sicily and its islands is possible."],
    continuity: ["Fewer connections and a shorter journey, bringing greater continuity to travel between places that share the same sea."],
    thought: ["Not changing the geography.", "Changing the way across."],
    islandsTitle: "From one shore to another.",
    islands: ["Two different islands. Two distinct identities. The same sea.", "CAURIS starts with the idea of making the journey between Sicily and these islands simpler, more direct and more natural."],
    closingTitle: ["The geography stays the same.", "The way across can change."],
    closing: "CAURIS Aviation begins with the idea of bringing a place and the possibility of reaching it closer together.",
    last: ["Sicily and its islands.", "Closer at last, in the journey too."],
    alts: ["A helicopter flying in the evening light above the water", "Sea and horizon seen through a helicopter window", "A helicopter rotor against the sky", "Coast and sea seen through a cockpit"],
  },
};

export default about;
